name: Discord Role Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./path/to/your/python/script

      - name: Run the bot
        run: |
          python discord-role-bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        working-directory: ./path/to/your/python/script
