name: Discord Role Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Specify Node.js version 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r path/to/your/python/script/requirements.txt
        working-directory: ./  # Change this to the root of your repository

      - name: Run the bot
        run: |
          python path/to/your/python/script/discord-role-bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
