name: XML Updater

on:
  push:
    branches:
      - main
    paths:
      - 'wuxu-complete.json'
      - 'wuxu-complete++.json'

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3
      shell: bash
    - name: Update XML
      run: |
        python3 xml-updater.py
      shell: bash
