name: Auto Update

on:
  schedule:
    - cron: "0 0 * * 1,4" # Runs every Monday and Thursday at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run update.py
      run: python update.py
