name: XML Updater

on:
  push:
    paths:
      - 'wuxu-complete.json'
      - 'wuxu-complete++.json'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run XML Updater
      run: python RSS Feed/xml-updater.py
