name: XML Updater

on:
  push:
    paths:
      - 'wuxu-complete.json'
      - 'wuxu-complete-plus.json'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run XML Updater
      run: python 'RSS Feed/xml-updater.py'
