name: XML Updater

on:
  push:
    paths:
      - 'wuxu-complete-plus.json'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Update XML
        run: python RSS\ Feed/xml-updater.py
      - name: Git add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '--all'
          default_author: github_actions
  
      
      
      
      
      
