name: XML Updater

on:
  push:
    paths:
      - 'wuxu-complete.json'
      - 'wuxu-complete-plus.json'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update XML
        run: python RSS\ Feed/xml-updater.py
